# Generated by Django 4.0.4 on 2022-05-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_returnbook_issued_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnbook',
            old_name='issued_id',
            new_name='issued_date',
        ),
    ]
