# Generated by Django 4.0.4 on 2022-05-19 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_returnbook_issued_date_alter_returnbook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbook',
            name='issuebook_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='home.issuebook'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnbook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
