# Generated by Django 4.0.4 on 2022-05-20 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_returnbook_issuebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnbook',
            name='issuebook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_book', to='home.issuebook'),
        ),
    ]
