# Generated by Django 4.0.4 on 2022-05-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_returnbook_issuebook_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='returnbook',
            name='student_id',
        ),
    ]
