# Generated by Django 4.0.4 on 2022-05-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_returnbook_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnbook',
            name='book',
            field=models.ManyToManyField(to='home.book'),
        ),
    ]
