# Generated by Django 4.0.4 on 2022-05-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_returnbook_issuebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnbook',
            old_name='issuebook',
            new_name='issuebook_id',
        ),
    ]
