# Generated by Django 4.0.4 on 2022-05-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_returnbook_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnbook',
            name='issuebook_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.issuebook'),
        ),
    ]
