# Generated by Django 4.0.4 on 2022-05-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_returnbook_issuebook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnbook',
            name='issuebook_id',
            field=models.IntegerField(),
        ),
    ]
