# Generated by Django 4.0.4 on 2022-05-21 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_returnbook_issuebook_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='student_id',
        ),
    ]
