# Generated by Django 4.0.4 on 2022-05-21 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_issuebook_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='student_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
