# Generated by Django 4.0.4 on 2022-05-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_issuebook_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
